# Generated by Django 4.2.8 on 2023-12-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('tipo_incidencia', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_incidencia', models.CharField(blank=True, max_length=50, null=True)),
                ('comentario', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'incidencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotfPers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'notf_pers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('comentario', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'notificacion',
                'managed': False,
            },
        ),
    ]
