# Generated by Django 4.2.8 on 2023-12-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geolocalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geolocalizacion', models.CharField(blank=True, max_length=50, null=True)),
                ('velocidad', models.FloatField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'geolocalizacion',
                'managed': False,
            },
        ),
    ]
